### ISSUE TITLE
Shade 50 hex code is broken and sometimes the colour gets a little mixed up too.

### ISSUE THREAD

**Issue by terryupton** [SimeonGriggs/tailwind-css-palette-generator#10]
Firstly, this is a great tool. So thank you for this. 
It is a great starting point to getting the right balance and colour scale.

I have however, noticed a few issues with the '50' shade and it seems to get a little confused.
Please see some screenshots to illustrate this.

<img width="1162" alt="Screenshot 2021-03-26 at 12 39 22" src="https://user-images.githubusercontent.com/5698596/112632669-51fc5d80-8e30-11eb-91c4-6d3f2bbc5660.png">
<img width="1275" alt="Screenshot 2021-03-26 at 12 40 05" src="https://user-images.githubusercontent.com/5698596/112632715-66405a80-8e30-11eb-8f92-ad459eab7e40.png">
<img width="1161" alt="Screenshot 2021-03-26 at 12 40 28" src="https://user-images.githubusercontent.com/5698596/112632774-78ba9400-8e30-11eb-8bc4-1d0e934e082f.png">
<img width="1164" alt="Screenshot 2021-03-26 at 12 40 55" src="https://user-images.githubusercontent.com/5698596/112632813-84a65600-8e30-11eb-93c7-d151b629951e.png">

Thought you might like to know about this in case you wish to fix it :-)

Thanks.

**Comment by SimeonGriggs** [comment]
You're correct. That _is_ odd. 

I should get back to rewriting this some day.

**Comment by pdevito3** [comment]
+1 also ran into this myself.

Echoing OP's comment. This is a *super* useful tool @SimeonGriggs. I'm adapting it for some calculated colors with a theming feature and this is saving me a ton of time. much appreciated!

**Comment by SimeonGriggs** [comment]
This is fixed in v2 :)

https://tailwind.simeongriggs.dev/purple/A855F7
