### ISSUE TITLE
Colors are not matching with tailwind colors

### ISSUE THREAD

**Issue by TheJenos** [SimeonGriggs/tailwind-css-palette-generator#16]
Hey I actually tried to create function get color shades but it also didn't match up with original tailwind colors from this site

https://tailwindcss.com/docs/customizing-colors

So I took a another approach. I use tensorflow.js and train a model. here is the results

https://thejenos.github.io/ImageFilterStealer-Tensorflowjs-/color.html

**Comment by SimeonGriggs** [comment]
That's clever! Thanks for sharing.

Yes this tool is automated so won't accurately recreate the original Tailwind palette – those are hand-made by Tailwind's excellent designers!
