### ISSUE TITLE
Recent update unmoors the stops from the target lightness

### ISSUE THREAD

**Issue by mikestopcontinues** [SimeonGriggs/tailwind-css-palette-generator#47]
A few days ago, I generated a palette that tried to approximate the correct lightness stops. It would "stretch" the palette to match.

<img width="1044" alt="Screenshot 2023-03-31 at 2 06 54 PM" src="https://user-images.githubusercontent.com/150434/229128156-3fdac7b8-8583-4f24-83f7-3fd56db9915b.png">

But today, I generated another that doesn't try to match the same steps.

<img width="1291" alt="Screenshot 2023-03-31 at 2 07 56 PM" src="https://user-images.githubusercontent.com/150434/229128382-16b5996b-f396-467d-9baf-a4d7d34dad1b.png">

I know this was probably an error, but if not—I really liked that functionality. It got me closer to the desired output. It would also be useful if you implement #18. Thoughts?

**Comment by SimeonGriggs** [comment]
Could you share the hex value for the 500?

**Comment by SimeonGriggs** [comment]
Actually, I've spotted it. The new logic only checks the distance of each `stop` away from each other in the array – not the value of the `stop` itself.

Thanks for reporting!

**Comment by SimeonGriggs** [comment]
Fixed in #49

**Comment by mikestopcontinues** [comment]
Thanks!!!
