### ISSUE TITLE
Weighted Distribution

### ISSUE THREAD

**Issue by kevnk** [SimeonGriggs/tailwind-css-palette-generator#5]
More of a topic of discussion: I've made [a change to my local copy](https://github.com/truefrontier/tailwind-css-palette-generator/blob/kevnk-tweaks/src/helpers/scales.js#L33) that instead of evenly distributing the colors on the lightness/luminance scale, it sort of bell curves them. So it looks more like this: 

<img width="444" alt="TailwindCSS Palette Generator 2020-09-12 12-04-49" src="https://user-images.githubusercontent.com/1181420/93000779-2d721100-f4f0-11ea-858a-21de186896bf.png">

(Looking at this image, it may be better if we make the extremes even closer to one another...)

The reason I did this was that I wanted the two extremes to be a little closer to each other so I could use them next to each other as background colors without them being so starkly different. This also adds more contrast between the middle ones which is nice for making callouts just different enough from each other. 

I'm using this to generate a palette for my site and I'm interested to see how it turns out. 

Any thoughts? If you think this would be useful, feel free to copy the code.

**Comment by SimeonGriggs** [comment]
Yeah I had wondered about adding a control to be able to adjust the scale of those differences, likewise with hue and saturation. But hadn’t put the time into solving it...

**Comment by SimeonGriggs** [comment]
I've rewritten the app but left the underlying logic the same. 

Would still like to add this sort of option eventually though to make the distribution linear-or-not. Closing this for now.
