### ISSUE TITLE
UI Examples with Generated Colors

### ISSUE THREAD

**Issue by JosNun** [SimeonGriggs/tailwind-css-palette-generator#6]
First of all, I'd like to say thanks for putting something like this together. It may not be as good as a designer-curated palette, but it's leaps and bounds ahead of anything I can come up with!

While the color preview is nice, I feel as if it lacks a "real-world" example of these colors in use. It'd be great if there were a couple of different colorful UIs that used the generated colors so the user could get a better feel of what they'd be like in a real app.

**Comment by SimeonGriggs** [comment]
Agreed. Something like that was on the long list of original ideas I had for this before abandoning it for some other side project. 😅

**Comment by JosNun** [comment]
I feel that 100% :laughing: not sure I'll have time in the near future, but would you be open to a PR that adds one?

**Comment by SimeonGriggs** [comment]
Yeah for sure!

Overall I feel like the design is pretty rough and there’s some things I’d like to do with global state but I’m not sure when I’d be getting back around to it. 
GitHub <notifications@github.com> wrote:
“I feel that 100% 😆 not sure I'll have time in the near future, but would you be open to a PR that adds one?”
