### ISSUE TITLE
Adding 50 variants

### ISSUE THREAD

**Issue by florianbouvot** [SimeonGriggs/tailwind-css-palette-generator#7]
Hi,

Can you add a 50 variants to follow TailwindCSS palette (https://tailwindcss.com/docs/customizing-colors#color-palette-reference)?

Thank you, Florian

**Comment by SimeonGriggs** [comment]
Not a bad idea. Haven't revisited this project in awhile...

**Comment by amitaibu** [comment]
@SimeonGriggs thanks for the project, it a good place to get some initial shades. a 50 variant would be great :)

**Comment by SimeonGriggs** [comment]
Added in #9 

But oh boy do I want to rewrite this entire thing.
